vich_uploader:
    db_driver: orm

    mappings:
       aliment_image:
           uri_prefix: /image/legumes
           upload_destination: '%kernel.project_dir%/public/image'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
